name: Send Email Reminders

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 min
  workflow_dispatch:      # Allows manual triggering

jobs:
  run-reminder-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reminders script
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: python reminders.py

      - name: Debug log
        if: always()
        run: echo "Reminders script completed"
