name: Send Task Reminders

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at 00 minutes
  workflow_dispatch:      # Allows manual trigger from GitHub Actions tab

jobs:
  send_reminder_emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reminder script
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          python reminders.py
