name: Send Email Reminders

on:
  schedule:
    - cron: '0 9 * * *'     # 5:00 AM EDT
    - cron: '0 0 * * *'     # 8:00 PM EDT
  workflow_dispatch:

jobs:
  run-reminder-script:
    runs-on: ubuntu-latest

    outputs:
      script: ${{ steps.set-script.outputs.script }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Determine which reminder script to run
        id: set-script
        run: |
          HOUR=$(date -u +"%H")
          if [ "$HOUR" -eq 9 ]; then
            echo "script=reminders-today.py" >> "$GITHUB_OUTPUT"
          elif [ "$HOUR" -eq 0 ]; then
            echo "script=reminders-tomorrow.py" >> "$GITHUB_OUTPUT"
          else
            echo "script=" >> "$GITHUB_OUTPUT"
            exit 0

      - name: Run reminders script
        if: steps.set-script.outputs.script != ''
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: python ${{ steps.set-script.outputs.script }}

      - name: Debug log
        if: always()
        run: echo "Reminders script completed"
