name: Send Email Reminders

on:
  schedule:
    - cron: '0 5 * * *'     # 5:00 AM UTC – run reminder_today.py
    - cron: '0 20 * * *'    # 8:00 PM UTC – run reminder_tomorrow.py
  workflow_dispatch:

jobs:
  run-reminder-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Determine which reminder script to run
        id: set-script
        run: |
          HOUR=$(date -u +"%H")
          if [ "$HOUR" -eq 5 ]; then
            echo "script=reminder-today.py" >> $GITHUB_OUTPUT
          elif [ "$HOUR" -eq 20 ]; then
            echo "script=reminder-tomorrow.py" >> $GITHUB_OUTPUT
          else
            echo "script=" >> $GITHUB_OUTPUT
            exit 0
        outputs:
          script: ${{ steps.set-script.outputs.script }}

      - name: Run reminders script
        if: steps.set-script.outputs.script != ''
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: python ${{ steps.set-script.outputs.script }}

      - name: Debug log
        if: always()
        run: echo "Reminders script completed"
