name: Send Email Reminders   # Name of the workflow, shows up in GitHub Actions tab 

on:
  schedule:
    # Run every day at 9:00 AM UTC (5:00 AM EDT) → send "today" reminders
    - cron: '0 9 * * *'
    # Run every day at 12:00 AM UTC (8:00 PM EDT) → send "tomorrow" reminders
    - cron: '0 0 * * *'
    # Run every hour → used for hourly reminders
    - cron: '0 * * * *'
  workflow_dispatch:          # Allows you to manually trigger this workflow from the GitHub Actions tab

jobs:
  run-reminder-script:
    runs-on: ubuntu-latest    # Runner environment (Linux VM provided by GitHub)

    outputs:                  # Define job outputs (used here to pass which script to run later)
      script: ${{ steps.set-script.outputs.script }}

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Restore database artifact (SQLite file) from last workflow run
      - name: Download database artifact
        uses: actions/download-artifact@v4
        with:
          name: task-database       # Must match the name used in the upload step
          path: instance            # Place inside instance/ folder
        continue-on-error: true     # Don’t fail if no artifact exists yet (first run)

      # Step 3: Set up Python 3.11 environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 4: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #  Step 5: Decide which reminder script should run based on current UTC hour
      - name: Determine which reminder script to run
        id: set-script
        run: |
          HOUR=$(date -u +"%H")   # Get the current UTC hour (00–23)
          if [ "$HOUR" -eq 9 ]; then
            # At 9:00 UTC → send today's reminders
            echo "script=reminders-today.py" >> "$GITHUB_OUTPUT"
          elif [ "$HOUR" -eq 0 ]; then
            # At 0:00 UTC → send tomorrow's reminders
            echo "script=reminders-tomorrow.py" >> "$GITHUB_OUTPUT"
          else
            # All other hours → send hourly reminders
            echo "script=reminders-hour.py" >> "$GITHUB_OUTPUT"
          fi   # required to close the if-block!

      # ✅ Step 6: Run the chosen Python script
      - name: Run remind
